### PR TITLE
Documents $HOME/.vnc/default.tigervnc format

### LINKED ISSUE #270: Documentation for ~/.vnc/default.tigervnc
Is there documentation somewhere about `~/.vnc/default.tigervnc`?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30829674-documentation-for-vnc-default-tigervnc?utm_campaign=plugin&utm_content=tracker%2F3557444&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F3557444&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jblaine**
Fixes #270

### CODE REVIEW

**Comment by CendioOssman** [comment]
I'm a bit cautious about promising too much about this file as I do consider it somewhat internal. The fact that is has the same format as the "regular" .tigervnc files is because it was easy to implement it that way, rather than some stable design.

But we lack documentation for the format when used in other places, so I guess this is an improvement over the current state of things.

**Comment by Corax26** [comment]
@CendioOssman why do you consider it internal? Is there any other way to configure vncviewer ? Anyhow thanks @jblaine for documenting it!

**Comment by CendioOssman** [comment]
That file is the backend storage for the GUI. I.e. the GUI is the canonical interface for it. Hence it might also be different when appropriate (e.g.  on Windows we store stuff in the registry rather than to such a file) and extended or changed.

This however leaves gaps in automating things. Right now I'd say using the command line arguments, or separate .tigervnc files is the way to go. A global configuration would perhaps also be desirable, which would most likely have to be officially documented and may influence the stance on the local configuration storage.

**Comment by Corax26** [comment]
Not sure I understand, is there a way to configure things persistently through the GUI? And how would you use a config file other than the default one for vncviewer?

**Comment by CendioOssman** [comment]
> Not sure I understand, is there a way to configure things persistently through the GUI?

Any changes you do in the options dialog are saved to default.tigervnc.

> And how would you use a config file other than the default one for vncviewer?

By using the "Load" and "Save as" buttons in the viewer.

**Comment by Corax26** [comment]
Oh sweet, thank you!

**Pull request merged**
