### PR TITLE
Add a basic gitignore

### PR DESCRIPTION
**Pull request by clbr**
I looked at #551, and made this by hand.

### CODE REVIEW

**Comment by clbr** [comment]
The ignore-everything-except-this-subdir logic doesn't work in the same
level, so that will have go to one level above (unix/.gitignore instead
of unix/xserver/.gitignore). Moving the other things.

**Comment by CendioOssman** [comment]
You sure? This seems to work for me:
```
$ cat unix/xserver/.gitignore 
/*
!/hw
/hw/*
!/hw/vnc
```

**Comment by clbr** [comment]
Oh, I tried with just "*", without the leading /. Trying now.

**Comment by clbr** [comment]
Yes, works, pushed.

**Comment by CendioOssman** [comment]
Great. Thanks.

**Pull request merged**
