### PR TITLE
java: Resize remote display when fullscreening on mac

### PR DESCRIPTION
**Pull request by erfanoabdi**
For complete Mac OS X 10.7 Lion Fullscreen Support:
Java applications on Lion and newer can opt into the Fullscreen window feature per-window.

This PR adds remote resizing support to the current lion FullScreen detector method

### CODE REVIEW

**Comment by bphinz** [comment]
So this is meant to fix the case where going from windowed mode to fullscreen doesn't trigger a remote resize?

**Comment by erfanoabdi** [comment]
> So this is meant to fix the case where going from windowed mode to fullscreen doesn't trigger a remote resize?

Yeah, looks like this without patch: 
image

**Comment by bphinz** [comment]
OK, I see the same thing but even with the patch.  I'm also getting exceptions.  Which version of java are you using?

**Comment by erfanoabdi** [comment]
hmm i'm using java 15 here

**Comment by bphinz** [comment]
Ah,  with the patch it works on connect but not on subsequent toggles of fullscreen, and those are when the exceptions are thrown.  I will do some debugging over the weekend.

**Comment by erfanoabdi** [comment]
ah, i'm on macOS 10.15 probably some api is changed in newer version
Please send exception logs here maybe i can help

**Comment by bphinz** [comment]
CConn: Using pixel format depth 24 (32bpp) little-endian rgb888
    Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException
    	at java.util.ArrayList$Itr.next(ArrayList.java:864)
    	at com.tigervnc.vncviewer.DesktopWindow.remoteResize(DesktopWindow.java:417)
    	at com.tigervnc.vncviewer.DesktopWindow.handleResizeTimeout(DesktopWindow.java:338)
    	at com.tigervnc.vncviewer.DesktopWindow$4.actionPerformed(DesktopWindow.java:114)
    	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    	at java.awt.EventQueue.access$500(EventQueue.java:97)
    	at java.awt.EventQueue$3.run(EventQueue.java:709)
    	at java.awt.EventQueue$3.run(EventQueue.java:703)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by bphinz** [comment]
Also, I have to build the releases with Java 8 because jar files aren't backwards compatible.

**Comment by CendioOssman** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
