### PR TITLE
Add Catalan translation

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by CendioOssman** [comment]
Thank you for your contribution. Unfortunately all our translations are handled by the translation project. You can submit your translation to the Catalan team here and it will get to us the proper way:

http://translationproject.org/team/ca.html

**Comment by rbuj** [comment]
Thanks for the info, but I don't have enough time for an application in translationproject.org, it's a pity.

**Comment by CendioOssman** [comment]
I believe they will in most cases accept one-off submissions as well.

**Comment by rbuj** [comment]
I just sent an email to Catalan team asking for application, and I completed also the FSF disclaimer. I'll send the translation to robot as soon as I'm accepted. Finally, I read the submission procedure and It doesn't seem very difficult. It seems to take a while for being accepted, despite this I think that you were right and I have to send it to TP.

**Pull request closed without merging**
