### PR TITLE
add systemd service files

### PR DESCRIPTION
**Pull request by graysky2**
Since systemd is ubiquitous these days, upstream should provide reliable service files.  This is my attempt at that.  I'm not sure where you want your Makefile to drop them though since both files require users to edit them.

### CODE REVIEW

**Comment by CendioOssman** [comment]
Have you looked at the service files that the distributions have created? It would be nice if everyone could agree on the same thing. :)

**Comment by graysky2** [comment]
Yes, I have based this PR on the one Fedora has provided (the system service) but I recently discovered a more simplistic method in the user session service.  To me, that is really the way to go.

If https://github.com/TigerVNC/tigervnc/issues/216 is ever implemented, I would recommend simply supplying the user service in `/usr/lib/systemd/user/` which wouldn't require any modification from the user wanting to run it.

**Comment by graysky2** [comment]
I am going to close this PR and make it part of a larger one wherein the service, changes to the perl script and man page are updated for your review.

**Comment by graysky2** [comment]
Superseded by https://github.com/TigerVNC/tigervnc/pull/221

**Pull request closed without merging**
