### PR TITLE
Fix viewer crash when cursor has not been set

### PR DESCRIPTION
**Pull request by grulja**
This is a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1038701. This is a patch we have been carrying for a while and it would be probably better to get it upstreamed. Just note I'm not the original author.

### CODE REVIEW

**Comment by CendioOssman** [comment]
This looks wrong. Under what circumstances can this happen? The code just above always sets cursor.

**Comment by grulja** [comment]
This is a patch which was added to Tigervnc 1.3.0 in Fedora by the previous maintainer. It's possible that the code changed since then and when I look at the code now, I also think shouldn't be necessary. However, is there a chance that Fl_RGB_Image() call returns a nullptr?

**Comment by CendioOssman** [comment]
I'm fairly sure C++ requires it to return something valid.

Perhaps things got confused with de1a3b95837379b023aa24d8626392838959d437?

**Comment by grulja** [comment]
> Perhaps things got confused with [de1a3b9](https://github.com/TigerVNC/tigervnc/commit/de1a3b95837379b023aa24d8626392838959d437)?

Indeed!! I just checked my git log for tigervnc and it seems that this change didn't apply so I tried to rebase it did it this way, while it actually didn't apply because it was already part of upstream. 

Good you found out. One less downstream patch to be dropped.

**Pull request closed without merging**
