### PR TITLE
Add gitignore

### PR DESCRIPTION
**Pull request by tequillaz**
Add stadard ignores for C, C++, Java, CMake.

Based on [github gitignore](https://github.com/github/gitignore) project

### CODE REVIEW

**Comment by CendioOssman** [comment]
Thank you, but personally I think this thing is massively excessive and difficult to work with. Could you reduce it to things that are actually relevant for TigerVNC?

**Comment by tequillaz** [comment]
TigerVNC doesn't use c-lang, it is possible to remove c-lang part. All
other parts, yes, they are huge but it is community experience in
c++/java/cmake usage. I think we must save c++/java/cmake parts.

7 дек. 2017 г. 12:43 ПП пользователь "Pierre Ossman (Work account)" <
notifications@github.com> написал:

Thank you, but personally I think this thing is massively excessive and
difficult to work with. Could you reduce it to things that are actually
relevant for TigerVNC?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TigerVNC/tigervnc/pull/551#issuecomment-349915313>, or mute
the thread

**Comment by CendioOssman** [comment]
There's a bunch of crap in the other ones as well. E.g. `*.d` and `*.mod`. So I'm still :-1: for just putting this massive template in.

**Comment by CendioOssman** [comment]
Thank you, a little bit better, but still lots of stuff left. I'd like to see this reduces to just the things we need. So please check the rest and remove the sections that are for things that we don't have in our project.

**Pull request closed without merging**
