### PR TITLE
Don't use GetMaster() as that symbol is no longer exported by xorg-x11.

### PR DESCRIPTION
**Pull request by twaugh**
This is against master, replacing #128 (which was against 1.4-branch).

### CODE REVIEW

**Comment by CendioOssman** [comment]
This won't work on anything older than 1.10 as far as I can tell.

**Comment by twaugh** [comment]
Just saw this:
http://lists.x.org/archives/xorg-devel/2015-February/045659.html

So maybe we can drop this PR after all?

**Comment by CendioOssman** [comment]
Works for me. I assume everyone out there is already doing some patches to the current versions of Xorg.

**Comment by bphinz** [comment]
On Thu, Feb 26, 2015 at 10:51 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> Works for me. I assume everyone out there is already doing some patches to
> the current versions of Xorg.
>
So should I be applying that patch to our builds?

-brian

**Comment by CendioOssman** [comment]
I assume so. I figured we did already or libvnc.so would never work. Or maybe this isn't an issue with older Xorg servers.

**Comment by bphinz** [comment]
On Tue, Mar 17, 2015 at 12:40 PM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> I assume so. I figured we did already or libvnc.so would never work. Or
> maybe this isn't an issue with older Xorg servers.
>
OK, will do.

**Comment by CendioOssman** [comment]
Hang on. No, you should not apply this. It is only relevant for libvnc.so. And it only affects Xorg, not Xvnc or libvnc.so. And since we do not ship Xorg, we cannot fix anything. It's the distributions that need to have the patch.

**Pull request closed without merging**
