### PR TITLE
Allow PasswordFile in vncviewer config

### LINKED ISSUE #983: Parameter PasswordFile not recognized in default.tigervnc
**Describe the bug**
Upon connection I get the error:

```
Parameters:  Unknown parameter PasswordFile on line 27 in file
              /home/rne/.vnc/default.tigervnc
```
**To Reproduce**
1. Add a line `PasswordFile=~/.vnc/passwd` to `~/.vnc/default.tigervnc`
2. Connect to a VNC server using vncviewer
3. Get the above error message
4. You have to enter the password manually

**Expected behavior**
1. No error message.
2. The password provided by the configured password file is used.

**Screenshots**
N/A

**Client:**
 - OS: Arch Linux
 - VNC client: TigerVNC (vncviewer)
 - VNC client version: 1.10.1-1
 - Client downloaded from: Official Arch Linux repos

**Server:**
 - OS: Arch Linux
 - VNC server: TigerVNC (x0vncserver)
 - VNC server version: 1.10.1-1
 - Server downloaded from: Official Arch Linux repos
 - Server was started using: systemd (`/usr/bin/x0vncserver -display :0 -passwordfile /var/lib/digsig/vncpasswd`)

**Additional context**
The manual under https://tigervnc.org/doc/vncviewer.html clearly states:

> −passwd, −PasswordFile password-file
> 
> If you are on a filesystem which gives you access to the password file used by the server, you can specify it here to avoid typing it in. It will usually be "~/.vnc/passwd".

as well as

> $HOME/.vnc/default.tigervnc
> 
> Default configuration options. This file must have a "magic" first line of "TigerVNC Configuration file Version 1.0" (without quotes), followed by simple <setting>=<value> pairs of your choosing. The available settings are those shown in this man page.

My configuration file is

```
$ cat ~/.vnc/default.tigervnc 
TigerVNC Configuration file Version 1.0

ServerName=REDACTED
X509CA=
X509CRL=
SecurityTypes=X509Plain,TLSPlain,X509Vnc,TLSVnc,X509None,TLSNone,VncAuth,None
DotWhenNoCursor=1
AutoSelect=1
FullColor=1
LowColorLevel=2
PreferredEncoding=Tight
CustomCompressLevel=0
CompressLevel=2
NoJPEG=0
QualityLevel=8
FullScreen=1
FullScreenAllMonitors=1
DesktopSize=
RemoteResize=1
ViewOnly=0
Shared=0
AcceptClipboard=1
SendClipboard=1
SendPrimary=1
MenuKey=F8
FullscreenSystemKeys=1
PasswordFile=~/.vnc/passwd
```

The actual output is:

```
TigerVNC Viewer 64-bit v1.10.1
Built on: 2019-12-27 09:17
Copyright (C) 1999-2019 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.

Tue Mar 24 10:21:56 2020
 Parameters:  Unknown parameter PasswordFile on line 27 in file
              /home/rne/.vnc/default.tigervnc
 DecodeManager: Detected 8 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       Connected to host 1017.terminals.homeinfo.intra port 5900
 CConnection: Server supports RFB protocol version 3.3
 CConnection: Using RFB protocol version 3.3
 CConn:       Connection failed: Too many security failures
```
I'd then manually have to enter the password.
Beware that the _Connection failed: Too many security failures_ is due to too many aborted connection attempts and is not the issue here.

I was also able to dertermine, that the configuration parameter `PasswordFile` is not listed in `parameterArray` here: https://github.com/TigerVNC/tigervnc/blob/master/vncviewer/parameters.cxx#L159

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/90616774-parameter-passwordfile-not-recognized-in-default-tigervnc?utm_campaign=plugin&utm_content=tracker%2F3557444&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F3557444&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by conqp**
Fixes #983

### CODE REVIEW

**Review by CendioOssman — CHANGES_REQUESTED** [review]
I don't think storing the password permanently on disk is a security practice we want to encourage like this.

What we can do is let the system **read** any parameter from the configuration, but not **write** them. That will allow people to use very custom config files if they want. But without having GUI users end up with settings they cannot modify.

**Comment by conqp** [comment]
Well, it does not store passwords, it merely stores a path to an optional password file. Only this path is being read and written. If you see any encouragement in this, I wonder why TigerVNC has a password file option in the first place.
As for the GUI, what do you deem missing? I explicitly added a text field to store the password file.

**Comment by CendioOssman** [comment]
The parameter is something legacy that we've inherited. I don't think it would ever be accepted as a new feature if we didn't already have it.

If we want to save passwords properly we should look at using some more secure storage, like GNOME keyring or the secure storage that exists on macOS and Windows.

**Comment by pkkrusty** [comment]
Any update on this? What's the current best practice for scripting a connection to start on boot, where the password can be stored somewhere? According to the man page, I can do something like `xtigervncviewer -passwd /home/pi/Desktop/passwdfile /home/pi/Desktop/test.tigervnc` where passwdfile is generated by `vncpasswd /home/pi/Desktop/passwdfile`

But when I try that it gives me `authentication failure`

**Pull request closed without merging**
