### PR TITLE
Add -FixedPointer parameter which prevents cursor bitmap updates

### PR DESCRIPTION
**Pull request by Levitator1**
I had problems with lost cursor bitmap updates, so I decided to add a switch which disables them altogether, keeping the default mouse cursor. The switch is called -FixedPointer. TODO: Update the man page. There is also a partial NetBeans project in ./vncviewer, for the purpose of code-browsing.

### CODE REVIEW

**Comment by samhed** [comment]
Hi @Levitator1, in general we want to avoid adding code to work around bugs in other software.

Have you looked further into why your cursor goes missing? What VNC server are you using?

You could also have a look at the option to TigerVNC's viewer called "DotWhenNoCursor". If enabled it will show a dot when the server doesn't send a cursor.

**Comment by Levitator1** [comment]
Hi,

The problem is not that the cursor is missing. The trouble is that bitmap
updates are lost or missing, so you get the wrong cursor bitmap until the
next successful update. The server is tigervncserver, provided here:
https://packages.debian.org/buster/tigervnc-standalone-server

I don't know at what point the bitmap updates are getting lost.

**Comment by CendioOssman** [comment]
In that case it's a bug that we should try to fix.

Have you tried using a different VNC client? We need to determine if this is a bug in the client or the server.

Could you give us details on how your system is set up so we can try to replicate it?

**Comment by Levitator1** [comment]
Initially, I used the tigervncclient that comes with Debian Buster and it
displayed the problem. So, I recompiled the latest client from the tigervnc
repo, and it displays the issue as well. I have tried other types of
client, but the ones that I looked at did not display cursor updates at all
-- just the default pointer. I am launching the server with:

*vncserver -rfbport 5901 -SecurityTypes Plain -localhost*

The session type is XFCE.

I am launching the client with:

.*/vncviewer localhost:1 -NoJpeg -MenuKey F10 -SecurityTypes Plain*

The client machine is an arm64 Chromebook running Debian Stretch under
Chrome OS. The server is an amd64 desktop computer running Debian Buster.

**Comment by Levitator1** [comment]
Correction: The client is Debian Stretch under Chrome OS.

**Comment by CendioOssman** [comment]
Hmmm... Can't say we have much experience running the client on ChromeOS. Do you have any other client device you could test with so we can see if that is the issue?

What other vnc client did you test? Both RealVNC and TightVNC should show the cursor correctly.

**Comment by CendioOssman** [comment]
Something does sound a bit off in that case. Please let us know how it goes once you've tested on a different machine.

**Comment by CendioOssman** [comment]
No update. Closing.

**Pull request closed without merging**
