### PR TITLE
Reference #838 - Adding better systemd integration

### PR DESCRIPTION
**Pull request by navysurfer**
Adding a few touches to the #838 pull from @CendioOssman.  Added CentOS 8 packaging which for some reason isn't in upstream but is in the distro's repo.  Made a few changes to the .travis folder and SPEC files to hopefully allow Travis-CI to finish building.

I'm only polishing.  For more detail, please refer to #838.

### CODE REVIEW

**Comment by CendioOssman** [comment]
This gets a bit confusing for github, so could you adjust the PR to be for `master` instead? RHEL 8 should be relevant there as well. Then I can look at rebasing my systemd branch so you can keep experimenting with that.

**Comment by navysurfer** [comment]
Not sure what you're asking.  PR currently is tigervnc/tigervnc.master < navysurfer/tigervnc.systemd.  would you like me to merge my systemd branch with my master then pull?

**Comment by navysurfer** [comment]
I think I understand now.  You'd like me to add the same packaging updates to `master`.  I can take a look at that tonight. The spec file will be different because of the pam.d additions I had to make, so will need to be adjusted. I'll make another pull against master when it's done.  Just let me know if I misunderstood.

**Comment by CendioOssman** [comment]
Right, sorry. Please adjust the commits so it doesn't contain any of the work from #838. Just the CentOS 8 stuff.

**Comment by navysurfer** [comment]
On it.

**Comment by navysurfer** [comment]
Pull request has been made.  Looking through the rest of your systemd commits, I don't think I'd change anything.  I have one selinux bug fix for you whenever you get it rebased.  Thanks for all the hard work.

**Pull request closed without merging**
