### PR TITLE
Windows JIS Keyboard Support

### PR DESCRIPTION
**Pull request by gsittyz**
Added vkey mappings for Japanese keyboards because the special keys for Japanese input do not work on TigerVNC currently.

### CODE REVIEW

**Comment by CendioOssman** [comment]
Thank you for your contribution. I'm having some issues getting Japanese layout working in Windows so I can test this. Could you share how you've set things up?

**Comment by gsittyz** [comment]
I think this instruction will help.
https://www.thewindowsclub.com/install-japanese-keyboard-on-windows-10

**Comment by CendioOssman** [comment]
For some reason it just throws errors on my main test machine. Fortunately it worked better on a second machine, so I've been able to test this.

Your mapping look fine, but there virtual key codes used are unfortunately not unique to Japanese so there is a problem with conflicts here.

I had a look at Firefox and they do a similar mapping, but only if the current layout is Japanese. So I think it's probably best if we do the same. I'll add some commits to your branch. Please have a look and see if you think it looks reasonable.

**Comment by CendioOssman** [comment]
@gsittyz ?

**Pull request merged**
